#!/bin/bash

#make clean; make

# Fixed 'low' / 'high' set of cloud top and bottom temperatures.
file="IWP_iterator.txt"
c=1
while IFS= read line
do
     if [ ${#c} -eq 1 ]; then
        cstr="0"$c
     else
        cstr=$c
     fi
     c=$((c+1))
     IWP=${line}
     echo $IWP
     ./rrtm_driver "IWP"${cstr}"_THI" $IWP
done <"$file"

# Fixed IWP and warm the cloud top temperature to 231 K.
#for CTT in {200..231}; do
#    echo $CTT
#    ./rrtm_driver "Tt_"$CTT $CTT 237
#done

# Fixed IWP and cool the cloud bottom temperature to 206 K.
#for CBT in {206..237}; do
#    echo $CBT
#    ./rrtm_driver "Tb_"$CBT 200 $CBT
#done

# Inject qi = 0.1 or 0.2 g kg-1 at different levels
#allThreads=(196 197 199 200 202 204 205 207 209 210 212 214 215 217
#	218 220 222 224 225 227 229 230 232 234 235 237 239 240 242
#	244 245 247 249 251 252 254 256 257 259 260 261 262 264 266
#	267 269 271)
#for i in {15..61}; do
#    indx=$((i-15))
#    echo "Run "$indx" of 46"
#    ./rrtm_driver ${allThreads[$indx]}_q2 $i 0.2e-03
#    ./rrtm_driver ${allThreads[$indx]}_q1 $i 0.1e-03
#    ./rrtm_driver ${allThreads[$indx]}_q01 $i 0.2e-04
#    ./rrtm_driver ${allThreads[$indx]}_q002 $i 0.2e-05
#done


